services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: 0NZBVzrg5Bu8
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DEBUG: "1"
      DATABASE_NAME: django_db
      DATABASE_USER: django_user
      DATABASE_PASSWORD: 0NZBVzrg5Bu8
      DATABASE_HOST: db
      DATABASE_PORT: 5432

  frontend:
    build:
      context: ./frontend
      #dockerfile: ../Dockerfile
    command: npm start
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
#    environment:
#      - REACT_APP_API_URL=${REACT_APP_API_URL}
    env_file:
      - ./frontend/.env.development # Use the corresponding environment file
    depends_on:
      - backend

volumes:
  postgres_data:

